[general]
enabled = yes
pretty = yes
; Formato de los timestamps en los eventos del WebSocket
allowed_origins = *

[${ARI_USER}]
type = user
read_only = no
password = ${ARI_PASSWORD}
password_format = plain
